In [2]:
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
# sentence
sent=['the glass of milk',
'the glass of juice',
'the cup of tea',
'I am a good boy',
'i am a good developer',
'understand the meaning of words',
'your videos are good']

In [4]:
# define the vocabulary
voc_size=10000

In [5]:
# one hot represintation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[9931, 9056, 8774, 5110],
 [9931, 9056, 8774, 8584],
 [9931, 612, 8774, 3081],
 [669, 2976, 464, 6715, 7555],
 [669, 2976, 464, 6715, 993],
 [632, 9931, 530, 8774, 3334],
 [3304, 9308, 5723, 6715]]

In [7]:
# word enbodding representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.utils import pad_sequences

In [8]:
import numpy as np

In [9]:
sent_length=8
embeded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
embeded_docs

array([[   0,    0,    0,    0, 9931, 9056, 8774, 5110],
       [   0,    0,    0,    0, 9931, 9056, 8774, 8584],
       [   0,    0,    0,    0, 9931,  612, 8774, 3081],
       [   0,    0,    0,  669, 2976,  464, 6715, 7555],
       [   0,    0,    0,  669, 2976,  464, 6715,  993],
       [   0,    0,    0,  632, 9931,  530, 8774, 3334],
       [   0,    0,    0,    0, 3304, 9308, 5723, 6715]], dtype=int32)

In [17]:
dim=10

In [18]:
#feature representaion
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

c:\Users\siddh\anaconda3\envs\myenv\Lib\site-packages\keras\src\layers\core\embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [20]:
model.summary()

Model: "sequential_6"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_5 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [21]:
model.predict(embeded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 316ms/step


array([[[ 1.25000589e-02, -4.64649908e-02,  4.40185927e-02,
          3.61097716e-02, -5.55454567e-03, -4.26204801e-02,
         -4.45860624e-02, -8.14870745e-03,  4.53423299e-02,
          3.31717171e-02],
        [ 1.25000589e-02, -4.64649908e-02,  4.40185927e-02,
          3.61097716e-02, -5.55454567e-03, -4.26204801e-02,
         -4.45860624e-02, -8.14870745e-03,  4.53423299e-02,
          3.31717171e-02],
        [ 1.25000589e-02, -4.64649908e-02,  4.40185927e-02,
          3.61097716e-02, -5.55454567e-03, -4.26204801e-02,
         -4.45860624e-02, -8.14870745e-03,  4.53423299e-02,
          3.31717171e-02],
        [ 1.25000589e-02, -4.64649908e-02,  4.40185927e-02,
          3.61097716e-02, -5.55454567e-03, -4.26204801e-02,
         -4.45860624e-02, -8.14870745e-03,  4.53423299e-02,
          3.31717171e-02],
        [-4.07323241e-02,  4.22500707e-02, -2.16018036e-03,
          2.13173665e-02, -2.31346842e-02, -9.84157249e-03,
         -6.48357719e-03,  4.06697430e-02,  2.035420

In [22]:
embeded_docs[0]

array([   0,    0,    0,    0, 9931, 9056, 8774, 5110], dtype=int32)